// Plain-text content for `vim <file>` mode.
// Maintained alongside the JSX sections — auto-extracting from JSX would be brittle.

export const viewContent = {
    home: [
        '# samuel-portfolio',
        '#',
        '# Welcome. This is a terminal.',
        '# Type `help` in the prompt for a list of commands.',
        '#',
        '',
        '## about',
        'Samuel Yoo — Software Development Engineer @ AWS',
        'Bse(Hons) Software Engineering, University of Auckland',
        'Auckland, New Zealand',
        '',
        '## links',
        'github   ➜ github.com/scy02718',
        'linkedin ➜ linkedin.com/in/chanyoo',
        'email    ➜ scy02718@gmail.com',
    ],

    about: [
        '# about.md',
        '#',
        '',
        '$ whoami',
        'samuel-yoo',
        '',
        '$ pwd',
        '/auckland/new_zealand',
        '',
        '$ cat profile.md',
        'Recent Software Engineering graduate from the University of',
        'Auckland (GPA 8.55 / 9.0). Strong problem solver, eager learner,',
        'building products that help people.',
        '',
        'Holds 3 AWS certifications and a deep background in software',
        'development practices. Joining AWS as an SDE.',
        '',
        '$ ls ./stack',
        'python   java   javascript   typescript   dart',
        'react    next   django       flask        docker',
        'pytorch  scipy  aws-suite',
    ],

    education: [
        '# education.md',
        '#',
        '',
        '## University of Auckland          [2021 - 2024]',
        'Bachelor of Engineering (Honours) in Software Engineering',
        '↳ GPA : 8.55 / 9.0',
        '',
        'First Class Honours. Mastered web development, machine',
        'learning, algorithms, and data structures through team',
        'projects and research.',
        '',
        '[skills] algorithms · web · machine learning',
        '',
        '## Westlake Boys High School      [2016 - 2020]',
        'High School Diploma',
        '↳ Rank Score: 320 / 320 (perfect)',
        '',
        'Top student in Mathematics and Physics. Outstanding',
        'Scholar Award. Strong teamwork and leadership through',
        'extracurricular activities.',
        '',
        '[skills] teamwork · leadership · problem solving',
    ],

    experience: [
        '# experience.md',
        '#',
        '',
        '## Amazon Web Services (AWS)             [2025 - Present]',
        'Software Development Engineer',
        '',
        '  Designing and implementing scalable, reliable software',
        '  solutions for AWS customers.',
        '',
        '## Align HealthTech Limited              [2024 - Present]',
        'Founding Member / Tech Lead',
        '',
        '  AI-SaaS platform that enhances consultation efficiency',
        '  for healthcare providers. Architecture, development,',
        '  and deployment.',
        '',
        '## Resideo NZ                            [2023 - 2024]',
        'Machine Learning Intern',
        '',
        '  Object detection models for smart home devices,',
        '  addressing housefire and fall risks.',
        '',
        '## University of Auckland                [2023]',
        'AI Research Assistant',
        '',
        '  Predicting Electrocardiographic signals from Body',
        '  Surface Potentials. Wearable device applications.',
    ],

    certificates: [
        '# certificates.md',
        '#',
        '',
        '7 AWS certifications + early adopter badges:',
        '',
        '  - AWS Certified Solutions Architect — Associate',
        '  - AWS Certified Developer — Associate',
        '  - AWS Certified Machine Learning Engineer — Associate',
        '  - AWS Certified Cloud Practitioner',
        '  - AWS Certified AI Practitioner',
        '  - AWS Certified Machine Learning Engineer — Early Adopter',
        '  - AWS Certified AI Practitioner — Early Adopter',
        '',
        'For details, scores, and credly links:',
        ':q then `cd certificates`',
    ],

    awards: [
        '# awards.md',
        '#',
        '',
        '## Industry Award — Best Part IV Project       [2024]',
        '   University of Auckland · CSL',
        '   Best Part IV project in Engineering, Robotics category.',
        '   Reward: NZD $500',
        '',
        '## 3rd Place — Velocity $100K Challenge        [2024]',
        '   University of Auckland · Velocity Innovation Hub',
        '   Startup competition — innovative business ideas.',
        '   Reward: NZD $15,000',
        '',
        "## Dean's Honours List           [2021, 2022, 2023, 2024]",
        '   University of Auckland',
        '   Top 5% of the faculty, 4 consecutive years.',
        '',
        '## Outstanding Scholar Award                   [2020]',
        '   NZQA',
        '   Top 30 students nationwide in NZQA Scholarship Exam.',
        '   Reward: NZD $15,000',
    ],

    skills: [
        '# skills.json',
        '#',
        '',
        '{',
        '  "languages": [',
        '    "python", "java", "javascript", "typescript",',
        '    "dart", "c#", "sql"',
        '  ],',
        '  "web": ["react", "next", "django", "flask"],',
        '  "ml":  ["pytorch", "scipy"],',
        '  "cloud": ["aws"],',
        '  "devops": ["docker"],',
        '  "strengths": [',
        '    "adaptability",',
        '    "problem-solving",',
        '    "resilience",',
        '    "leadership"',
        '  ]',
        '}',
    ],

    contact: [
        '# contact.md',
        '#',
        '',
        '$ cat contact.md',
        '',
        'Drop a message — I read every one.',
        '',
        '  email     scy02718@gmail.com',
        '  github    github.com/scy02718',
        '  linkedin  linkedin.com/in/chanyoo',
        '  instagram instagram.com/samuel.yoo_',
        '',
        'Or :q and `cd contact` to use the form.',
    ],
}

export const fileNames = () => Object.keys(viewContent)

// Parse `vim <arg>` arg into a clean view name. Strips ./, ~/, .md, .txt.
export const parseFileName = (raw) => {
    if (!raw) return null
    let name = raw.trim()
    name = name.replace(/^\.\//, '').replace(/^~\//, '')
    name = name.replace(/\.(md|txt)$/i, '')
    return name in viewContent ? name : null
}

export const fileBytes = (lines) => lines.reduce((s, l) => s + l.length + 1, 0)
